gnb_id: 147

slicing:
 - sst: 1
   sd: 0

amf:
  addr:  10.42.0.44
  bind_addr: 192.168.0.104

ru_sdr:
  device_driver: bladerf
  device_args: "rx_gain=manual"
  # clock:
  # sync:
  srate: 23.040
  otw_format: sc16
  tx_gain: 66
  rx_gain: 15

cell_cfg:
  dl_arfcn: 634000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "001001"
  tac: 1
  pci: 1
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 4
    nof_dl_slots: 2
    nof_dl_symbols: 7
    nof_ul_slots: 1
    nof_ul_symbols: 6
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam256
    max_ue_mcs: 27
  pucch:
    sr_period_ms: 4

e2:
  enable_du_e2: false
  e2sm_kpm_enabled: false
  e2sm_rc_enabled: false
  addr: 10.42.1.7
  bind_addr: 10.42.1.6
  port: 36421

log:
  filename: stdout
  all_level: info

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap