amf:
  addr: 192.168.0.154
  bind_addr: 192.168.0.71

rf_driver:
  device_driver: lime
  device_args:
  clock:
  sync:
  srate: 23.04
  otw_format: sc12
  tx_gain: 50
  rx_gain: 60

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
      
log:
  filename: stdout
  all_level: info
  radio_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
